<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework> <!-- 建议针对 Windows 优化 -->
    <Nullable>enable</Nullable>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <!-- GPLv3 信息 -->
    <Authors>CreatorCSIE</Authors>
    <PackageLicenseExpression>GPL-3.0-or-later</PackageLicenseExpression>
    <OutputPath>..\..\build\</OutputPath>
    <!-- 禁用在输出路径后自动追加框架名称（如 net8.0-windows） -->
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <!-- 禁用在输出路径后自动追加运行环境名称 -->
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <AvaloniaResource Include="favicon.ico" />
    <AvaloniaResource Include="favicon.png" />
    <AvaloniaResource Include="68942543.png" />
    <AvaloniaResource Include="logo_small.svg" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.0" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.0" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.0" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.0" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.2" />
    <PackageReference Include="Avalonia.Diagnostics" Version="11.0.10" />
    <PackageReference Include="FluentAvaloniaUI" Version="2.4.1" />
    <PackageReference Include="Avalonia.Svg.Skia" Version="11.3.0" />
    <!-- 必须添加注册表支持 -->
    <PackageReference Include="Microsoft.Win32.Registry" Version="5.0.0" />
  </ItemGroup>
</Project>
